author: Rahul Katariya
author_url: https://twitter.com/rahulkatariya91
github_url: https://github.com/Restofire/Restofire
root_url: https://Restofire.github.io/Restofire/
module: Restofire
output: docs
theme: fullwidth
xcodebuild_arguments: [-workspace, 'Restofire.xcworkspace', -scheme, 'Restofire-iOS']
