language: objective-c
osx_image: xcode7.2

before_install:
  - brew update
  - brew upgrade carthage

install:
  - carthage bootstrap

script:
  xcodebuild test -project Reactofire.xcodeproj
    -scheme Reactofire-iOS
    -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.4'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.3'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.2'
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1'

  xcodebuild test -project Reactofire.xcodeproj
    -scheme Reactofire-Mac
    -sdk macosx ONLY_ACTIVE_ARCH=NO
    -destination 'arch=x86_64'

  xcodebuild test -project Reactofire.xcodeproj
    -scheme Reactofire-watchOS
    -sdk watchsimulator ONLY_ACTIVE_ARCH=NO
    -destination 'name=Apple Watch - 38mm,OS=2.1'
    -destination 'name=Apple Watch - 38mm,OS=2.0'

  xcodebuild test -project Reactofire.xcodeproj
    -scheme Reactofire-tvOS
    -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO
    -destination 'name=Apple TV 1080p,OS=9.1'
    -destination 'name=Apple TV 1080p,OS=9.0'
