language: objective-c
osx_image: xcode7.2

script:
  xcodebuild test -project Reactofire.xcodeproj
    -scheme Reactofire-iOS
    -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2'

