language: objective-c
osx_image: xcode7.2

before_install: gem install cocoapods -v '= 0.39.0'

script:
   - xcodebuild test -workspace Reactofire.xcworkspace -scheme Reactofire -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
