language: objective-c
osx_image: xcode7.3

install:
  - carthage update Nimble Quick --platform iOS --no-use-binaries
  - carthage update Alamofire --no-use-binaries

script:
  - xcodebuild clean test -project Restofire.xcodeproj
    -scheme Restofire-iOS
    -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    -destination 'name=iPhone 6,OS=9.3'
